### ISSUE TITLE
Doesn't work after last update

### ISSUE THREAD

**Issue by e-jim** [YunoHost-Apps/mautrix_telegram_ynh#41]
Hello,

After the last update, my /opt/yunohost/mautrix_telegram/config.yaml was all messed up:

- the database config line didn't have credentials in it nor the database name:
`    database: postgres://:@localhost:5432`
instead of
`    database: postgres://mautrix_telegram:SOMEPASSWORD@localhost:5432/mautrix_telegram`

So the service would yield this error:

`python3[1894136]: asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "mautrix_telegram`

- The as_token, hs_token and shared_secret value were also different the previously.
Which would cause another problem: 
`python3[1896155]: [2022-12-06 12:44:35,258] [CRITICAL@mau.init] The as_token was not accepted. Is the registration file installed in your homeserver correctly?`

- The line
`my_matrix_hostname.tld: puppeting`
was replaced by 
`local: puppeting`

 

I could fix the issue restoring the config.yaml file from the backups and it all worked fine afterwards.
I just don't have the latest version of it.

I'm not sure whether I had made any manual change in this file before, but I don't think so.

**Comment by thardev** [comment]
Hi @e-jim 

I experienced the same when I updated to the latest version... I thought it happened because of manual modifications that I did in my config file but it seems not :(
Regarding where the issue comes from it seems that on some latest changes we forgot to add some values for backwards compatibility in the upgrade script so it kinda breaks those vars values... 
I'll take care of fixing it.

Regarding the restoring of your previous config file from the backup it is fine. If you want to have the latest version you can actually get the values of `mautrix_bridge_db_name` and `mautrix_bridge_db_pwd` using:
`sudo yunohost app setting mautrix_telegram mautrix_bridge_db_name`
`sudo yunohost app setting mautrix_telegram mautrix_bridge_db_pwd`
And for the `as_token` and `hs_token` you can find the values in `/etc/matrix-synapse/app-service/mautrix_telegram.yaml`
And the copy them to the latest version of the config file.
I hope this helps!

**Comment by e-jim** [comment]
Upgrade didn't immediately work for me, because the line
`my_matrix_hostname.tld: puppeting`
was replaced by
`local: puppeting`

If guess the equivalent of 
```
if [ "$botusers" = "local" ]
then
	botusers="$server_name"
fi
```

from the install script should find its way to the upgrade script (the botuser setting is well assigned on yunohost level)
